export default {
    SPLASH: 'Splash',
    HOME: 'Home',
    CUSTOMERS_TAB: 'CustomersTab',
    CUSTOMERS: 'CustomersScreen',
    CUSTOMER_DETAIL: 'CustomerDetailScreen',
    ADD_CUSTOMER: 'AddCustomerScreen',
    JOBS_TAB: 'JobsTab',
    JOBS: 'JobsScreen',
    JOB_DETAIL: 'JobDetailScreen',
    ADD_JOB: 'AddJobScreen',
    CREATE_INVOICE: 'InvoiceScreen',
    TEAM_TAB: 'TeamTab',
    TEAM: 'Team',
    ANALYTICS_TAB: 'AnalyticsTab',
    ANALYTICS: 'AnalyticsScreen',
    INBOX_TAB: 'InboxTab',
    INBOX: 'Inbox',
    CHAT_DETAIL: "ChatDetail",
    WELCOME: "Welcome",
    ACCOUNT: "Account",
    SIGN_IN: "SignIn",
    PHONE_VERIFICATION_SCREEN: "PhoneVerificationScreen",
    ADD_MEMBER: "AddMemberScreen"
  }
  